#ifndef SAMSUNGSMARTTVWEBPLUGIN_GLOBAL_H
#define SAMSUNGSMARTTVWEBPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAMSUNGSMARTTVWEBPLUGIN_LIBRARY)
#  define SAMSUNGSMARTTVWEBPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAMSUNGSMARTTVWEBPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAMSUNGSMARTTVWEBPLUGIN_GLOBAL_H
